#ifndef CIRCLE_TABLE_H
#define CIRCLE_TABLE_H

/* 360 precomputed points on a circle, radius 95, centered on the
   320x200 hi-res bitmap (160,100) -- generated by
   tools/gen_circle_table.py, see src/circle_table.c. Both axes fit in
   a byte (x: 65..255, y: 5..195), so indexing by degree (0..359) costs
   nothing at runtime beyond a table lookup -- no sin/cos, no runtime
   trig, matching the same "precompute once" approach as hires.c's
   ROW_OFFSET. */

extern const unsigned char CIRCLE_X[360];
extern const unsigned char CIRCLE_Y[360];

#endif
