#!/usr/bin/env python3
"""Generates src/note_table.c: SID voice frequency-register values for
three-and-a-bit chromatic octaves (C3-C6), so main.c/song.c never need
runtime float math to turn a note into a SID register write.

SID formula: register value = note_freq_hz * 2^24 / clock_hz. Clock
here is the PAL C64's ~985248.4Hz (VICE's x64sc default -- what this
project's `make run` actually launches); an NTSC machine's ~1.0227MHz
clock would need a different table (about 3.8% higher pitch if this
one were used unchanged there).

Usage: tools/gen_note_table.py > src/note_table.c
"""

PAL_CLOCK_HZ = 985248.4
A4_HZ = 440.0
A4_MIDI = 69  # MIDI note number for A4 (middle-C octave = 4, C4 = MIDI 60)

NOTE_NAMES = ["C", "CS", "D", "DS", "E", "F", "FS", "G", "GS", "A", "AS", "B"]
FIRST_OCTAVE = 3
LAST_OCTAVE = 6  # only C6 itself is emitted from this octave

names = []
freqs = []

for octave in range(FIRST_OCTAVE, LAST_OCTAVE + 1):
    for i, name in enumerate(NOTE_NAMES):
        if octave == LAST_OCTAVE and i > 0:
            break  # stop right after C6
        midi = (octave + 1) * 12 + i  # C-1 = MIDI note 0
        hz = A4_HZ * (2.0 ** ((midi - A4_MIDI) / 12.0))
        reg = round(hz * (1 << 24) / PAL_CLOCK_HZ)
        assert 0 <= reg <= 0xFFFF, (name, octave, reg)
        names.append(f"NOTE_{name}{octave}")
        freqs.append(reg)

print("/* Generated by tools/gen_note_table.py -- do not hand-edit.")
print("   SID voice frequency-register values, one per chromatic note")
print(f"   from {names[0]} to {names[-1]}, computed for the PAL C64's")
print(f"   ~{PAL_CLOCK_HZ / 1000:.4f}kHz clock. See note_table.h. */")
print()
print('#include "note_table.h"')
print()
print("const unsigned NOTE_FREQ[NUM_NOTES] = {")
for i in range(0, len(freqs), 8):
    row = ", ".join(str(v) for v in freqs[i:i + 8])
    print(f"    {row},")
print("};")
