/* Generated by tools/gen_note_table.py -- do not hand-edit.
   SID voice frequency-register values, one per chromatic note
   from NOTE_C2 to NOTE_C6, computed for the PAL C64's
   ~985.2484kHz clock. See note_table.h. */

#include "note_table.h"

const unsigned NOTE_FREQ[NUM_NOTES] = {
    1114u, 1180u, 1250u, 1324u, 1403u, 1487u, 1575u, 1669u,
    1768u, 1873u, 1985u, 2103u, 2228u, 2360u, 2500u, 2649u,
    2807u, 2973u, 3150u, 3338u, 3536u, 3746u, 3969u, 4205u,
    4455u, 4720u, 5001u, 5298u, 5613u, 5947u, 6300u, 6675u,
    7072u, 7493u, 7938u, 8410u, 8910u, 9440u, 10001u, 10596u,
    11226u, 11894u, 12601u, 13350u, 14144u, 14985u, 15876u, 16820u,
    17820u,
};
