#!/usr/bin/env python3
"""Generates src/ship_table.c: the ship's 6-point outline, precomputed
at every 1-degree rotation (360 orientations), as signed pixel offsets
from the ship's own center -- zero runtime trig, same "precompute once"
approach as vector-scene/src/circle_table.c.

Base outline (from the JS prototype's ship polygon, normalized units):
  [[1,0],[-0.9,0.7],[-0.6,0.5],[-0.6,-0.5],[-0.9,-0.7],[1,0]]
A simple wedge/arrow shape, closed (first point repeats as last),
6 points already the size needed for the 5-segment outline.

Usage: tools/gen_ship_table.py > src/ship_table.c
"""

import math

SHIP_SCALE = 10
N_POINTS = 6
N_ANGLES = 360

BASE = [
    (1.0, 0.0),
    (-0.9, 0.7),
    (-0.6, 0.5),
    (-0.6, -0.5),
    (-0.9, -0.7),
    (1.0, 0.0),
]

dx_table = []  # [angle][point]
dy_table = []

for angle in range(N_ANGLES):
    rad = math.radians(angle)
    c, s = math.cos(rad), math.sin(rad)
    row_dx = []
    row_dy = []
    for (x, y) in BASE:
        rx = x * c - y * s
        ry = x * s + y * c
        dx = round(rx * SHIP_SCALE)
        dy = round(ry * SHIP_SCALE)
        assert -128 <= dx <= 127 and -128 <= dy <= 127, (angle, dx, dy)
        row_dx.append(dx)
        row_dy.append(dy)
    dx_table.append(row_dx)
    dy_table.append(row_dy)


def emit(name, table):
    print(f"const signed char {name}[{N_ANGLES}][{N_POINTS}] = {{")
    for row in table:
        vals = ", ".join(str(v) for v in row)
        print(f"    {{ {vals} }},")
    print("};")
    print()


print("/* Generated by tools/gen_ship_table.py -- do not hand-edit.")
print(f"   Ship outline (6 points, {SHIP_SCALE}px scale), precomputed at all")
print("   360 one-degree rotations, as signed offsets from the ship's own")
print("   center. See ship_table.h. */")
print()
print('#include "ship_table.h"')
print()
emit("SHIP_DX", dx_table)
emit("SHIP_DY", dy_table)
