#!/usr/bin/env python3
"""Generates src/circle_table.c: 360 precomputed points on a circle,
radius 95, centered on the 320x200 hi-res bitmap (160,100) -- one point
per whole degree. Not run by the Makefile (the C64 toolchain has no
Python dependency); this is a one-off, reproducible way to derive the
table committed as src/circle_table.c, in the same "precompute once,
don't re-derive on the 6502" spirit as hires.c's ROW_OFFSET.

Both x (160+-95 = 65..255) and y (100+-95 = 5..195) fit in a single
unsigned byte, so the table is 360 bytes per axis, not 720.

Usage: tools/gen_circle_table.py > src/circle_table.c
"""

import math

CENTER_X = 160
CENTER_Y = 100
RADIUS = 95
N = 360

xs = []
ys = []
for deg in range(N):
    rad = math.radians(deg)
    x = round(CENTER_X + RADIUS * math.cos(rad))
    y = round(CENTER_Y + RADIUS * math.sin(rad))
    assert 0 <= x <= 255, (deg, x)
    assert 0 <= y <= 255, (deg, y)
    xs.append(x)
    ys.append(y)


def emit(name, values):
    print(f"const unsigned char {name}[{N}] = {{")
    for i in range(0, N, 20):
        row = ", ".join(str(v) for v in values[i:i + 20])
        print(f"    {row},")
    print("};")
    print()


print("/* Generated by tools/gen_circle_table.py -- do not hand-edit.")
print(f"   {N} points on a circle, radius {RADIUS}, centered at "
      f"({CENTER_X},{CENTER_Y}) -- one per whole degree, angle 0 = "
      "positive x-axis, increasing clockwise on screen (since screen y "
      "increases downward). See circle_table.h. */")
print()
print('#include "circle_table.h"')
print()
emit("CIRCLE_X", xs)
emit("CIRCLE_Y", ys)
