#!/usr/bin/env python3
"""Generates src/note_table.h and src/note_table.c: SID voice
frequency-register values from C2 through F7, so main.c/pattern.c
never need runtime float math to turn a note into a SID register
write. Wider than o-come-all-ye-faithful-c64's C2-C6 because this
source MIDI (a "music box"-voiced arrangement) uses all 4 of its parts
in an unusually high register -- "lead" and "countermelody 2" both run
up past C6, peaking at MIDI 101 (F7). B7 and above would overflow
SID's 16-bit frequency register (register value doubles per octave:
C6=~17820, C7=~35640, B7 would be ~67000+), so this stops at F7 with a
little headroom rather than a full octave 7.

SID formula: register value = note_freq_hz * 2^24 / clock_hz. Clock
here is the PAL C64's ~985248.4Hz (VICE's x64sc default -- what this
project's `make run` actually launches); an NTSC machine's ~1.0227MHz
clock would need a different table (about 3.8% higher pitch if this
one were used unchanged there).

Usage: tools/gen_note_table.py h > src/note_table.h
       tools/gen_note_table.py c > src/note_table.c
"""

import sys

PAL_CLOCK_HZ = 985248.4
A4_HZ = 440.0
A4_MIDI = 69  # MIDI note number for A4 (middle-C octave = 4, C4 = MIDI 60)

NOTE_NAMES = ["C", "CS", "D", "DS", "E", "F", "FS", "G", "GS", "A", "AS", "B"]
FIRST_OCTAVE = 2
LAST_MIDI = 101  # F7 -- the highest note this song's source MIDI actually uses

names = []
freqs = []

midi = (FIRST_OCTAVE + 1) * 12  # C-1 = MIDI note 0
while midi <= LAST_MIDI:
    octave, i = midi // 12 - 1, midi % 12
    hz = A4_HZ * (2.0 ** ((midi - A4_MIDI) / 12.0))
    reg = round(hz * (1 << 24) / PAL_CLOCK_HZ)
    assert 0 <= reg <= 0xFFFF, (NOTE_NAMES[i], octave, reg)
    names.append(f"NOTE_{NOTE_NAMES[i]}{octave}")
    freqs.append(reg)
    midi += 1

mode = sys.argv[1] if len(sys.argv) > 1 else "c"

if mode == "h":
    print("#ifndef NOTE_TABLE_H")
    print("#define NOTE_TABLE_H")
    print()
    print(f"/* Chromatic note indices {names[0][5:]}-{names[-1][5:]} into NOTE_FREQ (SID")
    print("   voice frequency-register values) -- generated by")
    print("   tools/gen_note_table.py, see note_table.c. NOTE_REST/HOLD")
    print("   (pattern.h) are deliberately not part of this enum: they're")
    print("   song-data sentinels, not real SID frequencies. */")
    print("enum {")
    for i in range(0, len(names), 8):
        row = ", ".join(names[i:i + 8])
        print(f"    {row},")
    print("    NUM_NOTES")
    print("};")
    print()
    print("extern const unsigned NOTE_FREQ[NUM_NOTES];")
    print()
    print("#endif")
else:
    print("/* Generated by tools/gen_note_table.py -- do not hand-edit.")
    print("   SID voice frequency-register values, one per chromatic note")
    print(f"   from {names[0]} to {names[-1]}, computed for the PAL C64's")
    print(f"   ~{PAL_CLOCK_HZ / 1000:.4f}kHz clock. See note_table.h. */")
    print()
    print('#include "note_table.h"')
    print()
    print("const unsigned NOTE_FREQ[NUM_NOTES] = {")
    for i in range(0, len(freqs), 8):
        # 'u' suffix: cc65's int is 16-bit signed (max 32767), so a
        # plain decimal literal above that -- routine once this table
        # reaches into octave 6+ -- otherwise parses as `long` and
        # warns before narrowing back to fit `unsigned`.
        row = ", ".join(f"{v}u" for v in freqs[i:i + 8])
        print(f"    {row},")
    print("};")
