#!/usr/bin/env python3
"""Generates src/pattern.c from reference/Christmas_Carols_-_We_Three_Kings.mid.

Same approach as the other c64-c-games SID player songs: soprano/alto/
bass per sixteenth-note row are the highest, second-highest, and
lowest of whatever's sounding at that instant, across this MIDI's 4
named parts (bass/lead/countermelody/countermelody 2 -- all one
"music box" instrument, one line each, no chords within a track,
unlike it-came-upon-a-midnight-clear-c64's chordal strings). Like that
one, this MIDI isn't quantized to a sixteenth-note grid -- it's an
expressive performance -- so note boundaries are rounded to the
nearest sixteenth (min 1 row long) rather than asserted exact.

Requires `mido` (pip install mido) -- tool-time only.

Usage: tools/gen_pattern.py > src/pattern.c
"""
import os

import mido

MIDI_PATH = os.path.join(os.path.dirname(__file__), "..", "reference",
                          "Christmas_Carols_-_We_Three_Kings.mid")
TRACK_NAMES = ["bass", "lead", "countermelody", "countermelody 2"]
ROWS_PER_MEASURE = 12  # 3/4 time: 3 beats * 4 sixteenths


def load_notes(path, track_names):
    mid = mido.MidiFile(path)
    tpb = mid.ticks_per_beat
    notes = []
    for track in mid.tracks:
        if track.name not in track_names:
            continue
        active = {}
        abs_tick = 0
        for msg in track:
            abs_tick += msg.time
            if msg.type == "note_on" and msg.velocity > 0:
                active[msg.note] = abs_tick
            elif msg.type == "note_off" or (msg.type == "note_on" and msg.velocity == 0):
                if msg.note in active:
                    notes.append({"note": msg.note, "start": active.pop(msg.note), "end": abs_tick})
    return notes, tpb


def separate_voices(notes, row_ticks, total_rows):
    for i, n in enumerate(notes):
        n["id"] = i
        n["row_start"] = round(n["start"] / row_ticks)
        n["row_end"] = max(n["row_start"] + 1, round(n["end"] / row_ticks))

    soprano = [None] * total_rows
    alto = [None] * total_rows
    bass = [None] * total_rows

    boundaries = sorted(set(n["row_start"] for n in notes) | set(n["row_end"] for n in notes))
    for r0, r1 in zip(boundaries, boundaries[1:]):
        if r0 >= total_rows:
            break
        r1 = min(r1, total_rows)
        active = sorted((n for n in notes if n["row_start"] <= r0 < n["row_end"]),
                         key=lambda n: -n["note"])
        if not active:
            continue
        for r in range(r0, r1):
            soprano[r] = active[0]
            alto[r] = active[1] if len(active) > 1 else active[0]
            bass[r] = active[-1]

    return soprano, alto, bass


NOTE_NAMES = ["C", "CS", "D", "DS", "E", "F", "FS", "G", "GS", "A", "AS", "B"]


def midi_to_note_macro(midi_num):
    return f"NOTE_{NOTE_NAMES[midi_num % 12]}{midi_num // 12 - 1}"


def voice_to_cells(voice):
    cells = []
    prev_id = None
    for n in voice:
        if n is None:
            cells.append("NOTE_REST")
            prev_id = None
        elif n["id"] == prev_id:
            cells.append("HOLD")
        else:
            cells.append(midi_to_note_macro(n["note"]))
            prev_id = n["id"]
    return cells


def main():
    notes, tpb = load_notes(MIDI_PATH, TRACK_NAMES)
    row_ticks = tpb // 4
    total_ticks = max(n["end"] for n in notes)
    total_rows = -(-total_ticks // row_ticks)  # ceil

    soprano, alto, bass = separate_voices(notes, row_ticks, total_rows)
    s_cells = voice_to_cells(soprano)
    a_cells = voice_to_cells(alto)
    b_cells = voice_to_cells(bass)

    print('#include "pattern.h"')
    print('#include "note_table.h"')
    print()
    print("/* Generated by tools/gen_pattern.py from")
    print("   reference/Christmas_Carols_-_We_Three_Kings.mid -- do not hand-edit.")
    print("   See that script's docstring for how the source's 4 named parts")
    print(f"   became the 3 voices below. One row = one sixteenth note;")
    print(f"   {ROWS_PER_MEASURE} rows = 1 measure (3/4 time). */")
    print()
    print("const pattern_row_t PATTERN[] = {")
    for i in range(total_rows):
        if i % ROWS_PER_MEASURE == 0:
            print(f"    /* measure {i // ROWS_PER_MEASURE + 1} */")
        s, a, b = s_cells[i], a_cells[i], b_cells[i]
        print(f"    {{ {s + ',':11s}{a + ',':11s}{b:10s} }},")
    print("};")
    print()
    print("const unsigned PATTERN_LENGTH = sizeof(PATTERN) / sizeof(PATTERN[0]);")


if __name__ == "__main__":
    main()
