/* Generated by tools/gen_note_table.py -- do not hand-edit.
   SID voice frequency-register values, one per chromatic note
   from NOTE_C3 to NOTE_C6, computed for the PAL C64's
   ~985.2484kHz clock. See note_table.h. */

#include "note_table.h"

const unsigned NOTE_FREQ[NUM_NOTES] = {
    2228, 2360, 2500, 2649, 2807, 2973, 3150, 3338,
    3536, 3746, 3969, 4205, 4455, 4720, 5001, 5298,
    5613, 5947, 6300, 6675, 7072, 7493, 7938, 8410,
    8910, 9440, 10001, 10596, 11226, 11894, 12601, 13350,
    14144, 14985, 15876, 16820, 17820,
};
