/* Generated by tools/gen_dir_table.py -- do not hand-edit.
   Unit direction (cos/sin) per heading, 24 headings
   (15 degrees apart), at two scales: thrust
   acceleration (*8) and bullet velocity
   (*640), both in the 1/64-pixel fixed-point scale
   main.c's positions use. See dir_table.h. */

#include "dir_table.h"

const signed char THRUST_DX[24] = {
    8, 8, 7, 6, 4, 2, 0, -2, -4, -6, -7, -8, -8, -8, -7, -6, -4, -2, 0, 2,
    4, 6, 7, 8,
};

const signed char THRUST_DY[24] = {
    0, 2, 4, 6, 7, 8, 8, 8, 7, 6, 4, 2, 0, -2, -4, -6, -7, -8, -8, -8,
    -7, -6, -4, -2,
};

const int BULLET_DX[24] = {
    640, 618, 554, 453, 320, 166, 0, -166, -320, -453, -554, -618,
    -640, -618, -554, -453, -320, -166, 0, 166, 320, 453, 554, 618,
};

const int BULLET_DY[24] = {
    0, 166, 320, 453, 554, 618, 640, 618, 554, 453, 320, 166,
    0, -166, -320, -453, -554, -618, -640, -618, -554, -453, -320, -166,
};

