#ifndef DIR_TABLE_H
#define DIR_TABLE_H

/* Unit-direction (cos/sin) tables per 1-degree heading, at the two
   scales main.c needs -- generated by tools/gen_dir_table.py, see
   dir_table.c. Zero runtime trig, same approach as circle_table.c/
   ship_table.c. */

extern const signed char THRUST_DX[360];
extern const signed char THRUST_DY[360];
extern const int BULLET_DX[360];
extern const int BULLET_DY[360];

#endif
