#ifndef SHIP_TABLE_H
#define SHIP_TABLE_H

/* Ship outline (6 points, 10px scale), precomputed at each of 24
   headings (15 degrees apart) -- generated by tools/gen_ship_table.py,
   see ship_table.c. SHIP_DX[heading][i]/SHIP_DY[heading][i] are signed
   pixel offsets from the ship's own center; add the ship's current
   world position to get screen coordinates for point i at the given
   heading (0-23). */

#define SHIP_POINTS 6
#define SHIP_HEADINGS 24

extern const signed char SHIP_DX[SHIP_HEADINGS][SHIP_POINTS];
extern const signed char SHIP_DY[SHIP_HEADINGS][SHIP_POINTS];

#endif
