#ifndef SHIP_TABLE_H
#define SHIP_TABLE_H

/* Ship outline (6 points, 10px scale), precomputed at every one-degree
   rotation -- generated by tools/gen_ship_table.py, see ship_table.c.
   SHIP_DX[angle][i]/SHIP_DY[angle][i] are signed pixel offsets from
   the ship's own center; add the ship's current world position to get
   screen coordinates for point i at the given heading (0-359). */

#define SHIP_POINTS 6

extern const signed char SHIP_DX[360][SHIP_POINTS];
extern const signed char SHIP_DY[360][SHIP_POINTS];

#endif
