#!/usr/bin/env python3
"""Generates src/dir_table.c: unit-direction tables for every 1-degree
heading (0..359), at two different scales -- thrust acceleration and
bullet velocity -- so neither the thrust nor the fire code needs
runtime trig or a runtime multiply/divide to rescale one table into
the other. Same "precompute once" approach as circle_table.c/
ship_table.c.

THRUST_DX/DY: cos/sin * SHIP_ACCEL, small enough for a signed byte.
BULLET_DX/DY: cos/sin * BULLET_SPEED, needs a signed int.

Both in the same 1/64-pixel fixed-point scale main.c's ship/bullet
positions use (POS_SHIFT = 6).

Usage: tools/gen_dir_table.py > src/dir_table.c
"""

import math

N_ANGLES = 360
SHIP_ACCEL = 8      # 0.125 units/frame * 64 (POS_SHIFT), rounded
BULLET_SPEED = 640  # 10 px/frame * 64 (POS_SHIFT)

thrust_dx, thrust_dy = [], []
bullet_dx, bullet_dy = [], []

for angle in range(N_ANGLES):
    rad = math.radians(angle)
    c, s = math.cos(rad), math.sin(rad)
    tdx = round(c * SHIP_ACCEL)
    tdy = round(s * SHIP_ACCEL)
    bdx = round(c * BULLET_SPEED)
    bdy = round(s * BULLET_SPEED)
    assert -128 <= tdx <= 127 and -128 <= tdy <= 127, (angle, tdx, tdy)
    assert -32768 <= bdx <= 32767 and -32768 <= bdy <= 32767, (angle, bdx, bdy)
    thrust_dx.append(tdx)
    thrust_dy.append(tdy)
    bullet_dx.append(bdx)
    bullet_dy.append(bdy)


def emit_byte(name, values):
    print(f"const signed char {name}[{N_ANGLES}] = {{")
    for i in range(0, N_ANGLES, 20):
        row = ", ".join(str(v) for v in values[i:i + 20])
        print(f"    {row},")
    print("};")
    print()


def emit_int(name, values):
    print(f"const int {name}[{N_ANGLES}] = {{")
    for i in range(0, N_ANGLES, 12):
        row = ", ".join(str(v) for v in values[i:i + 12])
        print(f"    {row},")
    print("};")
    print()


print("/* Generated by tools/gen_dir_table.py -- do not hand-edit.")
print(f"   Unit direction (cos/sin) per 1-degree heading, at two scales:")
print(f"   thrust acceleration (*{SHIP_ACCEL}) and bullet velocity")
print(f"   (*{BULLET_SPEED}), both in the 1/64-pixel fixed-point scale")
print("   main.c's positions use. See dir_table.h. */")
print()
print('#include "dir_table.h"')
print()
emit_byte("THRUST_DX", thrust_dx)
emit_byte("THRUST_DY", thrust_dy)
emit_int("BULLET_DX", bullet_dx)
emit_int("BULLET_DY", bullet_dy)
